[IMP] runbot_merge: handling of invalid path in patch
Trying to `git archive` a path which does not exist in the repository
leads to `git archive` sending an error on stderr and nothing on
stdout, which then leads to `tarfile` failing with

    tarfile.ReadError: empty file

which is pretty confusing for the patch author.

Check for the requested files with `ls-tree` before trying to
`archive`, and report a clearer error in case there are paths we can't
find.

Fixes #1279